library(umap)
umapData <- readRDS("/var/analysis/input/levelExprs.rds")
print(paste0("Number of columns: ", ncol(umapData)))
print(paste0("Number of rows: ", nrow(umapData)))
print("Starting UMAP")
uampOutput <- umap(umapData)
print("UMAP complete.")
print("Writing output.")
saveRDS(umapOutput,"/var/analysis/output/umapResult.rds")
